name       : fotoxx
version    : '19.14'
release    : 33
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-19.14.tar.gz : 8c9120f1a2eb9303ff1138943c597259574179fc7d6140f351f037046e05cc3f
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
