name       : fotoxx
version    : '20.19'
release    : 51
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-20.19.tar.gz : e6b631c4c5c6f94389f9b91c1b5a88c84988939a46314b6278a911caa320bf79
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
setup      : |
    %patch -p0 < $pkgfiles/drop-locales.patch
build      : |
    %make
install    : |
    %make_install
