name       : fotoxx
version    : '20.04'
release    : 42
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-20.04.tar.gz : 0d40ca190f6d9e7138a21b74e8f359068180027ebbfdecefd422070cd14ed56e
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
