name       : fotoxx
version    : 16.06.1
release    : 7
source     :
    - http://kornelix.net/downloads/tarballs/fotoxx-16.06.1.tar.gz : 932a4c761513ffb96609b4f8c39ea05aab3c9add6ebd844b56e95cd94fe0b2ec
license    : GPL-3.0+
summary    : Fotoxx image editing and collection management
component  : desktop.multimedia
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
