name       : fotoxx
version    : '22.20'
release    : 61
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-22.20.tar.gz : 6fbdb67963de0c62f0fa3d13fee7591074b1826a37d4dde36f6015b7f12bb8bb
homepage   : https://kornelix.net/fotoxx/fotoxx.html
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
