name       : fotoxx
version    : '16.07'
release    : 9
source     :
    - http://kornelix.net/downloads/tarballs/fotoxx-16.07.tar.gz : 056463198fa68785efe1c541c1b796ba6819e2cce2638c09944591b9f2aa75cb
license    : GPL-3.0+
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
