name       : fotoxx
version    : '19.17'
release    : 36
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-19.17.tar.gz : 0da39c534205b6a8124a8191b2004d6deb56f1862077449e84733fa3a307408c
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
