name       : fotoxx
version    : '19.19'
release    : 39
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-19.19.tar.gz : 1f00747cf9218c428bc6a226af0257bcab9053ccdef98224bb31a7ae79f75efe
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
