name       : fotoxx
version    : '20.05'
release    : 43
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-20.05.tar.gz : b4cee923867879b673e9fec65e9c3280e8f28dfa9e73cc8fd102dbd24743e9ea
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
