name       : fotoxx
version    : '20.10'
release    : 45
source     :
    - https://kornelix.net/downloads/downloads/fotoxx-20.10.tar.gz : aeda1fd679d9093568005ee0d32c64d48d3d4f817a41d5b3b22e0fa9eba3870a
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - xdg-utils
rundeps    :
    - dcraw
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
