name       : fotoxx
version    : 17.01.1
release    : 14
source     :
    - http://www.kornelix.net/downloads/tarballs/fotoxx-17.01.1.tar.gz : c063fbc66a2f6045b5837fe23d7ac28157b3c96006703136abed7060e707e9e3
license    : GPL-3.0
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - xdg-utils
rundeps    :
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
