name       : fotoxx
version    : 16.01.1
release    : 2
source     :
    - http://kornelix.net/downloads/tarballs/fotoxx-16.01.1.tar.gz : ab603754df821b9a21f759c4f5a0a95701a957778fd2729c14eae0c364e08871
license    : GPL-3.0+
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use. 
rundeps    :
    - dcraw
    - perl-image-exiftool
builddeps  :
    - pkgconfig(gtk+-3.0)
    - xdg-utils
    - pkgconfig(libtiff-4)
    - pkgconfig(libpng)
    - pkgconfig(lcms2)
build      : |
    %make
install    : |
    %make_install
