name       : fotoxx
version    : 18.01.4
release    : 20
source     :
    - https://kornelix.net/downloads/tarballs/fotoxx-18.01.4.tar.gz : aca96ffe064bdeec9532133ef63cace7257166ceacd2ad3658e98abe7d4c1e48
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Fotoxx image editing and collection management
description: |
    Fotoxx is a free open source Linux program for photo and image editing and collection management. The goal is to meet the needs of serious photographers while remaining fast and easy to use.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - xdg-utils
rundeps    :
    - perl-image-exiftool
build      : |
    %make
install    : |
    %make_install
